### ISSUE TITLE
Error - 'Unsupported Preset mode' when setting manual target temp

### ISSUE THREAD

**Issue by mutasim** [tonyroberts/hawundasmart#10]
When setting a manual target temperature the error below appears and preset mode is set to 'null'.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:45:46 pm (3 occurrences)
Last logged: 10:45:46 pm

[140337819701696] Unsupported Preset mode
[140337625076672] Unsupported Preset mode
[140337622834112] Unsupported Preset mode
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wundasmart/climate.py", line 328, in async_set_preset_mode
    raise NotImplementedError(f"Unsupported Preset mode {preset_mode}")
NotImplementedError: Unsupported Preset mode 
```

I guess we need a preset mode called manual that is set when a temp is manually set?

If this is the case, the do we need to define the behaviour of what happens when that preset is user selected? If so, then I think the behaviour when switching from auto -> heat works quite nice -  the target temp is set to 2 deg above current temp (rounded to the nearest whole number I think).

**Comment by tonyroberts** [comment]
What's the error when setting the mode to off? I'd guess the climate service is trying to set the preset mode to None, in which case it should just be a case of updating that set preset method to accept None

**Comment by tonyroberts** [comment]
Looks like this is specific to whatever climate card you're using since the default climate card doesn't seem to call the set preset service when changing the temperature or turning off. It's an easy fix though, I just can't reproduce the problem using the default climate card.

**Comment by mutasim** [comment]
Ah ok - I’m using the native tile card with climate entity. Issue only appears when the preset is added a ‘feature’, which offers up a selector. 

![IMG_2337](https://github.com/tonyroberts/hawundasmart/assets/365801/a8ef70dc-acfb-40c0-8cb6-3936c7967146)

Can confirm that if I remove preset as a ‘feature’ and only show in ‘appearance’ as a label then the error doesn’t appear.

**Comment by tonyroberts** [comment]
👍 should be fixed now

**Comment by mutasim** [comment]
Great works as expected 👍👍

**Comment by tonyroberts** [comment]
btw @mutasim, are you using wundasmart underfloor heating? I only delved down this rabbit hole after switching from a uponor system to wundasmart. I found that the 'smart' ufh controller was far from smart and over-shoots massively. I contacted wunda support and they confirmed it just switches on when the temp's below the set temp and off when it's above (minus the switching diff). Some of my rooms have at least a 2 hour lag and so that control method isn't adequate. I found their marketing pretty misleading as it talks about smart controls and temperature modulation, but it turns out for the UFH component it does none of that :(

**Comment by mutasim** [comment]
That’s annoying as they make out like they have sophisticated smart controls..

I’ve got one UFH zone live at the mo (and 4 TRV zones), 4 more UFH zones will come, pending house refurb. 

I’ve noticed it does massively overshoot which can make the room uncomfortably hot- haven’t given much thought to how to address this yet. 

![IMG_2338](https://github.com/tonyroberts/hawundasmart/assets/365801/25449768-f6fb-44ce-897f-b92d4c591b75)


You mentioned a PID library on the Hass forum. I’ve installed it, not yet set it up. Has that helped? Can you run it in parallel with the Wunda scheduling & presets or are you bypassing the lot?

**Comment by tonyroberts** [comment]
Yeah I'm in the process of migrating everything to the HASmartThermostat control. I'm reasonably confident that will work better, but tuning it for each room takes time so I'm doing it one room at a time.

I'm not using the wundasmart presets or schedules for the rooms I've moved over. Instead I use the smart thermostat to turn the heating on or off via a switch template. For each room there are two climate entities (the wunda one and the smart one) and this switch. The switch sets the temperature on the wundasmart climate entity to just above the smart thermostat climate entity when on, and then to the min temperature when off, allowing the smart thermostat to modulate the heating. I then use a scheduler in HA to do all the heating scheduling. I also have automations so that if the temperature is changed manually on either climate entity it keeps the two in sync.

Its all a lot more complicated than I would like, though what finally gets exposed in HA is fine. Hopefully wunda will improve their controller one day (something as simple as looking at the temperature 1st derivative would be enough) and I can scrap a lot of what I've done!

**Comment by tonyroberts** [comment]
@mutasim you should contact wundasmart support above the over-shooting. If they hear the same problem from a few people maybe they will look at improving it.

**Comment by mutasim** [comment]
Are you using the native schedule helper entity to store your schedules?

Does that leave you with min & on as your two states? 

Have you played with any away mode automations that override the schedule?

**Comment by tonyroberts** [comment]
also I opened discussions on this repo so happy to move the conversation to there if that's easier! :)
