### ISSUE TITLE
Startup logs throwing two warnings

### ISSUE THREAD

**Issue by mutasim** [tonyroberts/hawundasmart#25]
`Entity None (<class 'custom_components.wundasmart.climate.Device'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.
`

`TEMP_CELSIUS was used from wundasmart, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'wundasmart' custom integration`

**Comment by tonyroberts** [comment]
Thanks for reporting. This was fixed in e6b1165c35aeba2938d287d60308c9bcae2d2285 and will be included in the next release. If you would like to test this out, you can select the "dev" release in HACS, and if you still see this or have further issues when using that release then please feel free to re-open this issue or create a new one.
